"""create usage log

Revision ID: 7d3eef957ca7
Revises: 
Create Date: 2026-09-06 16:03:51.912136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d3eef957ca7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cache_hit', sa.Boolean(), nullable=False),
    sa.Column('fallback_used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ai_gateway'
    )
    op.create_index(op.f('ix_ai_gateway_usage_log_api_key_hash'), 'usage_log', ['api_key_hash'], unique=False, schema='ai_gateway')
    op.create_index(op.f('ix_ai_gateway_usage_log_created_at'), 'usage_log', ['created_at'], unique=False, schema='ai_gateway')
    op.create_index(op.f('ix_ai_gateway_usage_log_user_id'), 'usage_log', ['user_id'], unique=False, schema='ai_gateway')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_gateway_usage_log_user_id'), table_name='usage_log', schema='ai_gateway')
    op.drop_index(op.f('ix_ai_gateway_usage_log_created_at'), table_name='usage_log', schema='ai_gateway')
    op.drop_index(op.f('ix_ai_gateway_usage_log_api_key_hash'), table_name='usage_log', schema='ai_gateway')
    op.drop_table('usage_log', schema='ai_gateway')
    # ### end Alembic commands ###
